version: "3.2"
services:
  benchmark:
    build: './benchmark/cb-repair'
    hostname: 'benchmark'
    extra_hosts:
      - "framework:10.12.77.3"
      - "genprog:10.12.77.4"
      - "mutapr:10.12.77.5"
      - "cquencer:10.12.77.6"
      - "ae:10.12.77.7"
    networks:
      backend:
        ipv4_address: 10.12.77.2
    volumes:
      - /tmp/shared:/shared
    restart: always
  framework:
    build: './'
    hostname: 'framework'
    extra_hosts:
      - "benchmark:10.12.77.2"
      - "genprog:10.12.77.4"
      - "mutapr:10.12.77.5"
      - "cquencer:10.12.77.6"
      - "ae:10.12.77.7"
    networks:
      backend:
        ipv4_address: 10.12.77.3
    volumes:
      - /tmp/shared:/shared
      - ./results:/SecureThemAll/results
    depends_on:
      - benchmark
    restart: always
  genprog:
    build: './repair_tools/genprog-code'
    hostname: 'genprog'
    extra_hosts:
      - "benchmark:10.12.77.2"
      - "framework:10.12.77.3"
    networks:
      backend:
        ipv4_address: 10.12.77.4
    volumes:
      - /tmp/shared:/shared
    depends_on:
      - benchmark
  mutapr:
    build: './repair_tools/mut-aprfl'
    hostname: 'mutapr'
    extra_hosts:
      - "benchmark:10.12.77.2"
      - "framework:10.12.77.3"
    networks:
      backend:
        ipv4_address: 10.12.77.5
    volumes:
      - /tmp/shared:/shared
    depends_on:
      - benchmark
  cquencer:
    build: './repair_tools/CquenceR'
    hostname: 'cquencer'
    extra_hosts:
      - "benchmark:10.12.77.2"
      - "framework:10.12.77.3"
    networks:
      backend:
        ipv4_address: 10.12.77.6
    volumes:
      - /tmp/shared:/shared
    depends_on:
      - benchmark
  ae:
    build: './repair_tools/genprog-code'
    hostname: 'ae'
    extra_hosts:
      - "benchmark:10.12.77.2"
      - "framework:10.12.77.3"
    networks:
      backend:
        ipv4_address: 10.12.77.7
    volumes:
      - /tmp/shared:/shared
    depends_on:
      - benchmark
networks:
  backend:
    ipam:
      config:
        - subnet: 10.12.77.0/24
